--- #YAML:1.0
name:               Proc-Parallel
version:            0.601
abstract:           Stream from multiple commands at once library and command
author:
    - David Muir Sharnoff <muir@idiom.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Eval::LineNumbers:    0
    File::Slurp::Remote:  0
    IO::Event:            0.704
    IO::Handle:           0
    List::Util:           0
    Module::Load:         0
    Scalar::Util:         0
    Tie::Function::Examples:  0
resources:
    repository:  http://github.com/muir/Proc-Parallel
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
