# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Proc-Parallel
version:      0.3
version_from: lib/Proc/Parallel.pm
installdirs:  site
requires:
    File::Slurp::Remote:           0
    IO::Event:                     0.704
    IO::Handle:                    0
    List::Util:                    0
    Scalar::Util:                  0
    Tie::Function::Examples:       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
